### ISSUE TITLE
es files are shipped too

### ISSUE THREAD

**Issue by robinweser** [bundled-es-modules/fela#1]
Just a quick ping here, maybe you're not aware of, but we already ship the es files with every fela package as well.

e.g. https://unpkg.com/fela@6.2.1/es/

Maybe that helps?

**Comment by daKmoR** [comment]
@bashmish can you pls check. thx :)

**Comment by bashmish** [comment]
@rofrischmann we are using these `@bundled-es-modules` mostly with the `polymer-cli`. Your ES modules are OK, but you are using 3rd party dependencies which are not ES module compatible. For example running this code with a polymer-cli's command `polymer serve`

```js
import { createRenderer } from 'fela';
// or directly
import createRenderer from 'fela/es/createRenderer.js';
```

I get this error

```
Error: The requested module '../../fast-loops/lib/arrayReduce.js' does not provide an export named 'default'
```

I do understand that we could have better tooling and switch to Webpack and have all dependencies compiled and optimised during build time and not install time like this. And we are working on it. But for now we have this as a sort of workaround. Not a perfect workaround tho.

**Comment by robinweser** [comment]
Alright, I see. Just wanted to mention that anyways - was pretty sure you got a reason to do that.
Just stumbled over this package by accident when I checked fela's dependents :P
